export const FETCH_CALENDAR_EVENTS = {
    SUCCESS: 'FETCH_CALENDAR_EVENTS_SUCCESS',
    REQUEST: 'FETCH_CALENDAR_EVENTS_REQUEST',
    FAILURE: 'FETCH_CALENDAR_EVENTS_FAILURE'
}

export const FETCH_PUBLIC_HOLIDAYS = {
    SUCCESS: 'FETCH_PUBLIC_HOLIDAYS_SUCCESS',
    REQUEST: 'FETCH_PUBLIC_HOLIDAYS_REQUEST',
    FAILURE: 'FETCH_PUBLIC_HOLIDAYS_FAILURE'
}

export const ADD_CALENDAR_EVENTS = {
    SUCCESS: 'ADD_CALENDAR_EVENTS_SUCCESS',
    REQUEST: 'ADD_CALENDAR_EVENTS_REQUEST',
    FAILURE: 'ADD_CALENDAR_EVENTS_FAILURE'
}