export const CALENDAR_EVENTS = {
    FETCH: {
        SUCCESS: 'FETCH_CALENDAR_EVENTS_SUCCESS',
        REQUEST: 'FETCH_CALENDAR_EVENTS_REQUEST',
        FAILURE: 'FETCH_CALENDAR_EVENTS_FAILURE'
    },
    ADD: {
        SUCCESS: 'ADD_CALENDAR_EVENTS_SUCCESS',
        REQUEST: 'ADD_CALENDAR_EVENTS_REQUEST',
        FAILURE: 'ADD_CALENDAR_EVENTS_FAILURE'
    }
}

export const PUBLIC_HOLIDAYS = {
    FETCH: {
        SUCCESS: 'FETCH_PUBLIC_HOLIDAYS_SUCCESS',
        REQUEST: 'FETCH_PUBLIC_HOLIDAYS_REQUEST',
        FAILURE: 'FETCH_PUBLIC_HOLIDAYS_FAILURE'
    },
    ADD: {
        SUCCESS: 'ADD_PUBLIC_HOLIDAYS_SUCCESS',
        REQUEST: 'ADD_PUBLIC_HOLIDAYS_REQUEST',
        FAILURE: 'ADD_PUBLIC_HOLIDAYS_FAILURE'
    }
}